<a href="https://colab.research.google.com/github/Jags-08/cs-notes/blob/main/data-mining-dataset-analysis-python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/student_admission_record_dirty.csv')

In [ ]:
df.isnull().sum()

Name                      10
Age                       10
Gender                    10
Admission Test Score      11
High School Percentage    11
City                      10
Admission Status          10
dtype: int64

In [ ]:
df.isna().sum()

Name                      10
Age                       10
Gender                    10
Admission Test Score      11
High School Percentage    11
City                      10
Admission Status          10
dtype: int64

In [ ]:
df.head(10)

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,Shehroz,24.0,Female,50.0,68.90,Quetta,Rejected
1,Waqar,21.0,Female,99.0,60.73,Karachi,NaN
2,Bushra,17.0,Male,89.0,NaN,Islamabad,Accepted
3,Aliya,17.0,Male,55.0,85.29,Karachi,Rejected
4,Bilal,20.0,Male,65.0,61.13,Lahore,NaN
5,Murtaza,23.0,Female,NaN,NaN,Islamabad,Accepted
6,Asad,18.0,Male,NaN,97.31,Multan,Accepted
7,Rabia,20.0,Female,82.0,55.67,Lahore,Accepted
8,Rohail,17.0,Male,64.0,NaN,Karachi,Accepted
9,Kamran,18.0,Male,53.0,98.98,Multan,Rejected

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    147 non-null    object
 1   Age                     147 non-null    float64
 2   Gender                  147 non-null    object
 3   Admission Test Score    146 non-null    float64
 4   High School Percentage  146 non-null    float64
 5   City                    147 non-null    object
 6   Admission Status        147 non-null    object
dtypes: float64(3), object(4)
memory usage: 8.7+ KB

In [ ]:
df.describe()

              Age  Admission Test Score  High School Percentage
count  147.000000            146.000000              146.000000
mean    19.680272             77.657534               75.684726
std      4.540512             16.855343               17.368014
min     -1.000000             -5.000000              -10.000000
25%     18.000000             68.250000               65.052500
50%     20.000000             79.000000               77.545000
75%     22.000000             89.000000               88.312500
max     24.000000            150.000000              110.500000

In [ ]:
df['City'] = df['City'].str.strip()

In [ ]:
df['City'] = df['City'].str.upper()

In [ ]:
df['City'] = df['City'].str.lower()

In [ ]:
df['City'] = df['City'].str.title()

In [ ]:
df['City'].unique()

array(['Quetta', 'Karachi', 'Islamabad', 'Lahore', 'Multan', nan,
       'Peshawar', 'Rawalpindi'], dtype=object)

In [ ]:
df['City'] = df['City'].fillna(df['City'].mode()[0])

In [ ]:
df['Admission Test Score'] = df['Admission Test Score'].fillna(df['Admission Test Score'].median())

In [ ]:
from numpy._core.defchararray import lower
Q1 = df['Admission Test Score'].quantile(0.25)
Q3 = df['Admission Test Score'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df = df[(df['Admission Test Score'] >= lower_bound) & (df['Admission Test Score'] <= upper_bound)]

In [ ]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [ ]:
df['smooth_column'] = df['Age'].rolling(window=3).mean()

In [ ]:
df.isnull().sum()

Name                      10
Age                        0
Gender                    10
Admission Test Score       0
High School Percentage    11
City                       0
Admission Status          10
smooth_column              2
dtype: int64

In [ ]:
df['Admission Status'] = df['Admission Status'].fillna(df['Admission Status'].mode()[0])

In [ ]:
df['High School Percentage'] = df['High School Percentage'].fillna(df['High School Percentage'].median())

In [ ]:
from numpy._core.defchararray import lower
Q2 = df['High School Percentage'].quantile(0.25)
Q4 = df['High School Percentage'].quantile(0.75)
IQR1 = Q4 - Q2

lower_bound1 = Q2 - 1.5 * IQR1
upper_bound1 = Q4 + 1.5 * IQR1

df = df[(df['High School Percentage'] >= lower_bound1) & (df['High School Percentage'] <= upper_bound1)]

In [ ]:
df['Name'] = df['Name'].fillna(df['Name'].mode()[0])

In [ ]:
df.isnull().sum()

Name                       0
Age                        0
Gender                    10
Admission Test Score       0
High School Percentage     0
City                       0
Admission Status           0
smooth_column              2
dtype: int64

In [ ]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [ ]:
df['smooth_column'] = df['Age'].rolling(window=3).mean()

In [ ]:
df.isna().sum()

Name                      0
Age                       0
Gender                    0
Admission Test Score      0
High School Percentage    0
City                      0
Admission Status          0
smooth_column             2
dtype: int64

In [ ]:
df['smooth_column'] = df['smooth_column'].fillna(df['smooth_column'].mean())

In [ ]:
df.isna().sum()

Name                      0
Age                       0
Gender                    0
Admission Test Score      0
High School Percentage    0
City                      0
Admission Status          0
smooth_column             0
dtype: int64

In [ ]:
df.head(10)

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status,smooth_column
0,Shehroz,24.0,Female,50.0,68.900,Quetta,Rejected,19.744598
1,Waqar,21.0,Female,99.0,60.730,Karachi,Rejected,19.744598
2,Bushra,17.0,Male,89.0,77.745,Islamabad,Accepted,20.666667
3,Aliya,17.0,Male,55.0,85.290,Karachi,Rejected,18.333333
4,Bilal,20.0,Male,65.0,61.130,Lahore,Rejected,18.000000
5,Murtaza,23.0,Female,79.0,77.745,Islamabad,Accepted,20.000000
6,Asad,18.0,Male,79.0,97.310,Multan,Accepted,20.333333
7,Rabia,20.0,Female,82.0,55.670,Lahore,Accepted,20.333333
8,Rohail,17.0,Male,64.0,77.745,Karachi,Accepted,18.333333
9,Kamran,18.0,Male,53.0,98.980,Multan,Rejected,18.333333