20240802243 Jagrut Joshi Batch: B3

In [6]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\Admin\Downloads\student_marks_1000_weekly_hours.csv")
df.head()

,Sr No.,Student Name,Study Hours (per week),Maths,Phys,Chem,Bio,Eng,SGPA,Grade
0,1,Ayaan Sharma,44.0,86,58,41,57,69,5.94,B
1,2,Ishita Joshi,36.3,75,59,49,62,63,6.00,B+
2,3,Myra Iyer,45.8,71,58,60,68,54,5.98,B
3,4,Reyansh Yadav,56.3,69,70,95,81,78,7.72,A
4,5,Nandini Patel,35.2,72,37,65,45,77,5.87,B

In [4]:
print("Dataset Shape:", df.shape)
print("\nDataset Info:\n")
df.info()

Dataset Shape: (1000, 10)

Dataset Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sr No.                  1000 non-null   int64
 1   Student Name            1000 non-null   object
 2   Study Hours (per week)  1000 non-null   float64
 3   Maths                   1000 non-null   int64
 4   Phys                    1000 non-null   int64
 5   Chem                    1000 non-null   int64
 6   Bio                     1000 non-null   int64
 7   Eng                     1000 non-null   int64
 8   SGPA                    1000 non-null   float64
 9   Grade                   1000 non-null   object
dtypes: float64(2), int64(6), object(2)
memory usage: 78.3+ KB

In [5]:
df.describe()

,Sr No.,Study Hours (per week),Maths,Phys,Chem,Bio,Eng,SGPA
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000
mean,500.500000,38.214400,65.952000,62.195000,59.90800,62.524000,69.495000,6.394340
std,288.819436,11.685012,13.821676,14.128361,14.38633,13.908158,14.014792,0.941617
min,1.000000,0.000000,23.000000,21.000000,20.00000,15.000000,25.000000,3.750000
25%,250.750000,30.200000,58.000000,53.000000,50.00000,54.000000,60.000000,5.730000
50%,500.500000,38.300000,66.000000,62.000000,60.00000,63.000000,69.000000,6.400000
75%,750.250000,45.800000,75.000000,72.000000,69.00000,71.000000,79.000000,7.080000
max,1000.000000,70.000000,100.000000,100.000000,100.00000,100.000000,100.000000,8.920000

In [6]:
def classify_data_type(series):
    if series.dtype == 'object':
        return "Qualitative"
    elif np.issubdtype(series.dtype, np.integer):
        return "Quantitative - Discrete"
    elif np.issubdtype(series.dtype, np.floating):
        return "Quantitative - Continuous"
    else:
        return "Unknown"

In [17]:
def identify_scale(column):
    col = column.lower()
    
    if col in ["student name", "grade"]:
        if col == "grade":
            return "Ordinal"
        return "Nominal"
    
    if col in ["maths", "phys", "chem", "bio", "eng"]:
        return "Interval"
    
    if col in ["study hours (per week)", "sgpa", "sr no."]:
        return "Ratio"

In [18]:
results = []

for col in df.columns:
    data_type = classify_data_type(df[col])
    scale = identify_scale(col)
    
    results.append([col, data_type, scale])
    
classification_df = pd.DataFrame(
    results,
    columns = ["Attribute", "Data Type", "Scale of Measurement"]
)
classification_df

                Attribute                  Data Type Scale of Measurement
0                  Sr No.    Quantitative - Discrete                Ratio
1            Student Name                Qualitative              Nominal
2  Study Hours (per week)  Quantitative - Continuous                Ratio
3                   Maths    Quantitative - Discrete             Interval
4                    Phys    Quantitative - Discrete             Interval
5                    Chem    Quantitative - Discrete             Interval
6                     Bio    Quantitative - Discrete             Interval
7                     Eng    Quantitative - Discrete             Interval
8                    SGPA  Quantitative - Continuous                Ratio
9                   Grade                Qualitative              Ordinal